server:
  port: 8080

spring:
  application:
    name: aopdemo
  datasource:
    username: nickz
    password: password
    url: jdbc:postgresql://postgres:5432/postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  liquibase:
    change-log: classpath:/db.changelog/db.changelog-master.yaml
